const jobs = [
  {
    id: 1,
    company: "Google",
    position: "Frontend Developer",
    location: "Remote",
    type: "Full Time",
    salary: "$130,000 - $175,000",
    description: "Build modern and responsive using HTML, CSS, and JavaScript frameworks.",
    status: "all",
  },
  {
    id: 2,
    company: "Amazon",
    position: "Backend Developer",
    location: "USA",
    type: "Full Time",
    salary: "$150,000 - $185,000",
    description: "Develop and maintain scalable APIs and server-side applications.",
    status: "all",
  },
  {
    id: 3,
    company: "Tesla",
    position: "Software Engineer",
    location: "California",
    type: "Full Time",
    salary: "$150,000 - $185,000",
    description: "Design and implement software solutions for automotive systems.",
    status: "all",
  },
  {
    id: 4,
    company: "Meta",
    position: "UI Designer",
    location: "Remote",
    type: "Contract",
    salary: "$100,000 - $115,000",
    description: "Create intuitive and visually appealing user interfaces for web applications.",
    status: "all",
  },
  {
    id: 5,
    company: "Netflix",
    position: "QA Engineer",
    location: "USA",
    type: "Full Time",
    salary: "$120,000 - $155,000",
    description: "Perform manual and automated testing to ensure software quality.",
    status: "all",
  },
  {
    id: 6,
    company: "Spotify",
    position: "Mobile Developer",
    location: "Remote",
    type: "Part Time",
    salary: "$130,000 - $165,000",
    description: "Develop and maintain mobile applications for iOS and Android platforms.",
    status: "all",
  },
  {
    id: 7,
    company: "Apple",
    position: "iOS Developer",
    location: "USA",
    type: "Full Time",
    salary: "$160,000 - $185,000",
    description: "Build, test, and maintain iOS applications using Swift and Objective-C. ",
    status: "all",
  },
  {
    id: 8,
    company: "Microsoft",
    position: "Cloud Engineer",
    location: "Remote",
    type: "Full Time",
    salary: "$150,000 - $195,000",
    description: "Design, deploy, and manage cloud infrastructure using Azure services.",
    status: "all",
  },
];
